### ISSUE TITLE
Drag and Drop not implemented for files and folders

### ISSUE THREAD

**Issue by asitemade4u** [teejee2008/polo#229] opened 2018-08-14 18:23 UTC
It would be convenient (and relevant to the usual behavior of file managers) to implement the drag and drop action:

1. Within a pane
2. Between different panes
3. Between the "external world" and Polo
Currently, none works in my (last) version of Polo/Ubuntu.

**Comment by makepanic** [comment] 2018-08-22 07:39
This is probably a duplicate of https://github.com/teejee2008/polo/issues/27

**Comment by teejee2008** [comment] 2018-08-29 11:56
Closing this one

**Closed** 2018-08-29 11:56 UTC

**Comment by asitemade4u** [comment] 2018-08-29 19:44
Are you sure?

Not implemented at least in the beta that went accessible thru the PPA 
two days ago.

Stephen Sinclair

**Comment by teejee2008** [comment] 2018-08-30 05:49
This is a duplicate of an existing item. Check #27 for the status.
