### ISSUE TITLE
gvfs remote paths not supported

### ISSUE THREAD

**Issue by Lupul** [teejee2008/polo#116] opened 2017-07-09 12:24 UTC
I have some gvfs mounted remote locations that I have bookmarked with Gnome-Files (Nautilus).
They do apear in polo bookmark sidepanel but I cannot open them: 

![image](https://user-images.githubusercontent.com/3596864/27993845-19c53174-64ba-11e7-8277-5631521a4d1b.png)

The urls are sftp://... , smb://... which should be supported natively by GIO file operations.
Is this a known limitation?

**Comment by teejee2008** [comment] 2017-07-09 13:21
Remote paths are not yet supported.

**Comment by teejee2008** [comment] 2017-07-09 13:26
Duplicate of #28

**Closed by teejee2008** 2017-07-09 13:26 UTC
